#cloud-config
autoinstall:
    version: 1
    locale: en_US
    keyboard:
        layout: br
    storage:
        layout:
            name: lvm
    identity:
        hostname: hostname
        username: username
        password: "$6$V/FBAaYUeYO5kho4$WWvRLCnrM/e/cGuhIv5XVVO.e3k9nKN2MRBs2TJ8qkVqgQUmTXyut6syKSaeWtWQZyKoDh65hqFwIlyL9g9EC1"
