#cloud-config
autoinstall:
  version: 1
  locale: "pt_BR.UTF-8"
  keyboard:
    layout: "br"
  timezone: "America/Sao_Paulo"
  identity:
    hostname: "sup-sup"
    username: "sante-sup"
    password: "$6$15BM3XbO0Ae.cwwE$Md2FRtPLofW4uzHQdDAbTXcsAOCnuCzqZbCY6b78.p47/vdNg1/W50vjDfEVzZPse1k4u/rceV9q7j9GfihlE0"
  ssh:
    install-server: true
    allow-pw: true
  storage:
    layout:
      name: direct
  codecs:
    install: true
  drivers:
    install: true
  snaps:
    - name: discord
      channel: stable
      classic: false
    - name: emote
      channel: stable
      classic: false
  updates: all
  shutdown: reboot
