#cloud-config
autoinstall:
    version: 1
    reporting:
        hook:
            type: webhook
            endpoint: http://example.com/endpoint/path
    early-commands:
        - ping -c1 198.162.1.1
    locale: en_US
    keyboard:
        layout: gb
        variant: dvorak
    storage:
        layout:
            name: lvm
    identity:
        hostname: hostname
        username: username
        password: $crypted_pass
    ssh:
        install-server: yes
