#cloud-config
autoinstall:
    version: 1
    locale: en_US
    keyboard:
        layout: gb
        variant: dvorak
    storage:
        layout:
            name: lvm
    identity:
        hostname: hostname
        username: username
        password: $crypted_pass
    ssh:
        install-server: yes
