#cloud-config
autoinstall:
  version: 1
  locale: "pt_BR.UTF-8"
  keyboard:
    layout: "br"
  timezone: "America/Sao_Paulo"
  identity:
    realname: 'Lucas'
    hostname: "sup-lucas"
    username: "sante-sup"
    password: "$6$V/FBAaYUeYO5kho4$WWvRLCnrM/e/cGuhIv5XVVO.e3k9nKN2MRBs2TJ8qkVqgQUmTXyut6syKSaeWtWQZyKoDh65hqFwIlyL9g9EC1"
  ssh:
    install-server: true
  storage:
    layout:
      name: lvm
      sizing-policy: all
  codecs:
    install: true
  drivers:
    install: true
  updates: all
  shutdown: reboot
  late-commands:
    - curtin in-target -- sh -c "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
    - curtin in-target -- apt update
    - curtin in-target -- apt -y upgrade
    - curtin in-target -- apt -y autoremove
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get -y upgrade
    - curtin in-target -- add-apt-repository -y ppa:obsproject/obs-studio
    - curtin in-target -- apt -y install obs-studio flameshot
    - curtin in-target -- apt-get -y -f install
