#cloud-config
autoinstall:
  version: 1
  locale: "pt_BR.UTF-8"
  keyboard:
    layout: "br"
  timezone: "America/Sao_Paulo"
  identity:
    realname: 'Nayane'
    hostname: "com-nayane"
    username: "sante-com"
    password: "$6$V/FBAaYUeYO5kho4$WWvRLCnrM/e/cGuhIv5XVVO.e3k9nKN2MRBs2TJ8qkVqgQUmTXyut6syKSaeWtWQZyKoDh65hqFwIlyL9g9EC1"
  ssh:
    install-server: true
  storage:
    layout:
      name: lvm
      sizing-policy: all
  codecs:
    install: true
  drivers:
    install: true
  snaps:
    - name: discord
      channel: stable
      classic: false
    - name: emote
      channel: stable
      classic: false
  updates: all
  user-data:
    apt:
      sources:
        obs-studio:
          source: 'ppa:obsproject/obs-studio'
    packages:
      - obs-studio
      - flameshot
  shutdown: reboot
